// Auto-generated by build.js — do not edit manually.
// Last run: 2026-03-20T12:22:20.314Z
const CHANGELOG = {
  "lastRun": "2026-03-20T12:22:20.314Z",
  "totalFiles": 2,
  "comparisons": [
    {
      "fromLabel": "spring2026-v1",
      "toLabel": "spring2026-v2",
      "fromVersion": 1,
      "toVersion": 2,
      "comparedAt": "2026-03-20T12:22:20.313Z",
      "added": [
        {
          "matchNum": "1284",
          "date": "04/19/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force M U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1286",
          "date": "04/26/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force N U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Northville High School - Northville High School",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1290",
          "date": "05/03/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force B U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1295",
          "date": "05/10/2026",
          "time": "13:00 EDT",
          "homeClub": "Otsego United Soccer, Inc.",
          "homeTeam": "Otsego United U17 Boys Spring '26",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ryder Elementary School - Ryder Elementary School Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1299",
          "date": "05/17/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Galway",
          "awayTeam": "Galway Soccer Club 18u Boys",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1301",
          "date": "05/22/2026",
          "time": "18:30 EDT",
          "homeClub": "Northern United Soccer Club",
          "homeTeam": "U19B White Lightning",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ridge/Jenkinsville - Field 3",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1308",
          "date": "05/31/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Capital CIty FC",
          "awayTeam": "Capital City U17 Boys Integrity",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1312",
          "date": "06/07/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force M U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Mayfield High School - Mayfield HS",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "removed": [
        {
          "matchNum": "1082",
          "date": "04/19/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Northern United Soccer Club",
          "awayTeam": "U19B White Lightning",
          "awayScore": "",
          "location": "Waterford-Halfmoon High School - HS Turf Field",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1088",
          "date": "04/26/2026",
          "time": "13:00 EDT",
          "homeClub": "Brunswick",
          "homeTeam": "Brunswick U19 Boys White CDYSL 2026",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Brunswick Soccer Club Fields - Field 3",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1089",
          "date": "05/03/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Capital CIty FC",
          "awayTeam": "Capital City U17 Boys Integrity",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1097",
          "date": "05/17/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force B U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Broadalbin Perth High School - BP Turf",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1104",
          "date": "05/29/2026",
          "time": "18:30 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force M U18B",
          "awayScore": "",
          "location": "Waterford-Halfmoon High School - HS Turf Field",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1106",
          "date": "06/07/2026",
          "time": "13:00 EDT",
          "homeClub": "Otsego United Soccer, Inc.",
          "homeTeam": "Otsego United U17 Boys Spring '26",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ryder Elementary School - Ryder Elementary School Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1111",
          "date": "06/14/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force N U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1115",
          "date": "06/16/2026",
          "time": "18:30 EDT",
          "homeClub": "Galway",
          "homeTeam": "Galway Soccer Club 18u Boys",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Galway Fields - Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "modified": [
        {
          "matchNum": "108",
          "row": {
            "matchNum": "108",
            "date": "04/30/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC Evolution U8 Boys Black 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U8 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - U8 A",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/27/2026",
              "to": "04/30/2026"
            }
          ]
        },
        {
          "matchNum": "633",
          "row": {
            "matchNum": "633",
            "date": "05/05/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC U12 Boys Yellow Jackets 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Reds (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - 5B",
            "division": "Division 4",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Clifton Common  - 3A",
              "to": "Clifton Common  - 5B"
            }
          ]
        },
        {
          "matchNum": "439",
          "row": {
            "matchNum": "439",
            "date": "05/11/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U10 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Clifton Park",
            "awayTeam": "CPSC U10 Girls Shooting Stars 25/26",
            "awayScore": "",
            "location": "MSYSL Fields - Field 2",
            "division": "Division 4",
            "age": "10",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/30/2026",
              "to": "05/11/2026"
            }
          ]
        },
        {
          "matchNum": "130",
          "row": {
            "matchNum": "130",
            "date": "05/19/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC Evolution U8 Grey 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U8 Girls Cherries (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - U8 B",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/18/2026",
              "to": "05/19/2026"
            },
            {
              "field": "Location",
              "from": "Clifton Common  - U8 A",
              "to": "Clifton Common  - U8 B"
            }
          ]
        },
        {
          "matchNum": "117",
          "row": {
            "matchNum": "117",
            "date": "06/06/2026",
            "time": "10:00 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U8 Girls Cherries (Spring 2026)",
            "homeScore": "",
            "awayClub": "New Scotland",
            "awayTeam": "New Scotland SC U8 coed",
            "awayScore": "",
            "location": "MSYSL Fields - Field 1",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/09/2026",
              "to": "06/06/2026"
            }
          ]
        },
        {
          "matchNum": "475",
          "row": {
            "matchNum": "475",
            "date": "06/13/2026",
            "time": "16:15 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC U10 Girls Shooting Stars 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U10 Girls (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - 7B",
            "division": "Division 4",
            "age": "10",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/11/2026",
              "to": "06/13/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "16:15 EDT"
            }
          ]
        }
      ]
    }
  ]
};
