// Auto-generated by build.js — do not edit manually.
// Last run: 2026-03-31T19:36:23.461Z
const CHANGELOG = {
  "lastRun": "2026-03-31T19:36:23.461Z",
  "totalFiles": 5,
  "comparisons": [
    {
      "fromLabel": "spring2026-v1",
      "toLabel": "spring2026-v2",
      "fromVersion": 1,
      "toVersion": 2,
      "comparedAt": "2026-03-31T19:36:23.459Z",
      "added": [
        {
          "matchNum": "1284",
          "date": "04/19/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force M U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1286",
          "date": "04/26/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force N U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Northville High School - Northville High School",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1290",
          "date": "05/03/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force B U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1295",
          "date": "05/10/2026",
          "time": "13:00 EDT",
          "homeClub": "Otsego United Soccer, Inc.",
          "homeTeam": "Otsego United U17 Boys Spring '26",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ryder Elementary School - Ryder Elementary School Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1299",
          "date": "05/17/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Galway",
          "awayTeam": "Galway Soccer Club 18u Boys",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1301",
          "date": "05/22/2026",
          "time": "18:30 EDT",
          "homeClub": "Northern United Soccer Club",
          "homeTeam": "U19B White Lightning",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ridge/Jenkinsville - Field 3",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1308",
          "date": "05/31/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Capital CIty FC",
          "awayTeam": "Capital City U17 Boys Integrity",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1312",
          "date": "06/07/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force M U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Mayfield High School - Mayfield HS",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "removed": [
        {
          "matchNum": "1082",
          "date": "04/19/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Northern United Soccer Club",
          "awayTeam": "U19B White Lightning",
          "awayScore": "",
          "location": "Waterford-Halfmoon High School - HS Turf Field",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1088",
          "date": "04/26/2026",
          "time": "13:00 EDT",
          "homeClub": "Brunswick",
          "homeTeam": "Brunswick U19 Boys White CDYSL 2026",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Brunswick Soccer Club Fields - Field 3",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1089",
          "date": "05/03/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Capital CIty FC",
          "awayTeam": "Capital City U17 Boys Integrity",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1097",
          "date": "05/17/2026",
          "time": "13:00 EDT",
          "homeClub": "Fulton United",
          "homeTeam": "Force B U18B",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Broadalbin Perth High School - BP Turf",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1104",
          "date": "05/29/2026",
          "time": "18:30 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force M U18B",
          "awayScore": "",
          "location": "Waterford-Halfmoon High School - HS Turf Field",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1106",
          "date": "06/07/2026",
          "time": "13:00 EDT",
          "homeClub": "Otsego United Soccer, Inc.",
          "homeTeam": "Otsego United U17 Boys Spring '26",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Ryder Elementary School - Ryder Elementary School Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1111",
          "date": "06/14/2026",
          "time": "13:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U17 Boys (Spring 2026)",
          "homeScore": "",
          "awayClub": "Fulton United",
          "awayTeam": "Force N U18B",
          "awayScore": "",
          "location": "MSYSL Fields - Field 4",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "1115",
          "date": "06/16/2026",
          "time": "18:30 EDT",
          "homeClub": "Galway",
          "homeTeam": "Galway Soccer Club 18u Boys",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U17 Boys (Spring 2026)",
          "awayScore": "",
          "location": "Galway Fields - Field 1",
          "division": "HS Boys Div 4",
          "age": "19",
          "gender": "Male",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "modified": [
        {
          "matchNum": "108",
          "row": {
            "matchNum": "108",
            "date": "04/30/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC Evolution U8 Boys Black 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U8 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - U8 A",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/27/2026",
              "to": "04/30/2026"
            }
          ]
        },
        {
          "matchNum": "633",
          "row": {
            "matchNum": "633",
            "date": "05/05/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC U12 Boys Yellow Jackets 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Reds (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - 5B",
            "division": "Division 4",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Clifton Common  - 3A",
              "to": "Clifton Common  - 5B"
            }
          ]
        },
        {
          "matchNum": "439",
          "row": {
            "matchNum": "439",
            "date": "05/11/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U10 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Clifton Park",
            "awayTeam": "CPSC U10 Girls Shooting Stars 25/26",
            "awayScore": "",
            "location": "MSYSL Fields - Field 2",
            "division": "Division 4",
            "age": "10",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/30/2026",
              "to": "05/11/2026"
            }
          ]
        },
        {
          "matchNum": "130",
          "row": {
            "matchNum": "130",
            "date": "05/19/2026",
            "time": "18:30 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC Evolution U8 Grey 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U8 Girls Cherries (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - U8 B",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/18/2026",
              "to": "05/19/2026"
            },
            {
              "field": "Location",
              "from": "Clifton Common  - U8 A",
              "to": "Clifton Common  - U8 B"
            }
          ]
        },
        {
          "matchNum": "117",
          "row": {
            "matchNum": "117",
            "date": "06/06/2026",
            "time": "10:00 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U8 Girls Cherries (Spring 2026)",
            "homeScore": "",
            "awayClub": "New Scotland",
            "awayTeam": "New Scotland SC U8 coed",
            "awayScore": "",
            "location": "MSYSL Fields - Field 1",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/09/2026",
              "to": "06/06/2026"
            }
          ]
        },
        {
          "matchNum": "475",
          "row": {
            "matchNum": "475",
            "date": "06/13/2026",
            "time": "16:15 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC U10 Girls Shooting Stars 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U10 Girls (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - 7B",
            "division": "Division 4",
            "age": "10",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/11/2026",
              "to": "06/13/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "16:15 EDT"
            }
          ]
        }
      ]
    },
    {
      "fromLabel": "spring2026-v2",
      "toLabel": "spring2026-v3",
      "fromVersion": 2,
      "toVersion": 3,
      "comparedAt": "2026-03-31T19:36:23.460Z",
      "added": [
        {
          "matchNum": "109",
          "date": "04/11/2026",
          "time": "18:30 EDT",
          "homeClub": "Rush NY- Albany",
          "homeTeam": "NY Rush Select 11G DPL",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U16G",
          "awayScore": "",
          "location": "Afrim's Sports Park - Afrim's Sports Park Field 2 - OUT",
          "division": "Upstate U16 Girls",
          "age": "16",
          "gender": "Female",
          "status": "Scheduled",
          "eventName": "Northeast Classic - Girls 2026"
        },
        {
          "matchNum": "126",
          "date": "04/12/2026",
          "time": "11:00 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U16G",
          "homeScore": "",
          "awayClub": "Empire State Youth Soccer Club",
          "awayTeam": "Alleycats NPL G11",
          "awayScore": "",
          "location": "Afrim's Sports Park - Afrim's Sports Park Field 3 - OUT",
          "division": "Upstate U16 Girls",
          "age": "16",
          "gender": "Female",
          "status": "Scheduled",
          "eventName": "Northeast Classic - Girls 2026"
        },
        {
          "matchNum": "720",
          "date": "04/22/2026",
          "time": "18:30 EDT",
          "homeClub": "Crane",
          "homeTeam": "FC Columbia (2026) U12 Girls Div 4",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U12 Girls (Spring 2026)",
          "awayScore": "",
          "location": "St Joseph Spiritual Center Mavis Fields - U12 Game Field",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "733",
          "date": "05/10/2026",
          "time": "17:45 EDT",
          "homeClub": "Rip Van Winkle",
          "homeTeam": "RVW U12 Girls Spring Travel 2026",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U12 Girls (Spring 2026)",
          "awayScore": "",
          "location": "Rip Van Winkle Soccer Field - Field 3",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "760",
          "date": "05/27/2026",
          "time": "18:30 EDT",
          "homeClub": "Rip Van Winkle",
          "homeTeam": "RVW U12 Girls Spring Travel 2026",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U12 Girls (Spring 2026)",
          "awayScore": "",
          "location": "Rip Van Winkle Soccer Field - Field 3",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "removed": [
        {
          "matchNum": "742",
          "date": "05/13/2026",
          "time": "18:30 EDT",
          "homeClub": "New Scotland",
          "homeTeam": "New Scotland SC U12 Girls",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U12 Girls (Spring 2026)",
          "awayScore": "",
          "location": "Voorheesville Satellite Fields - 2",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "757",
          "date": "05/27/2026",
          "time": "18:30 EDT",
          "homeClub": "Mechanicville-Stillwater",
          "homeTeam": "MSUSC U12 Girls (Spring 2026)",
          "homeScore": "",
          "awayClub": "Crane",
          "awayTeam": "FC Columbia (2026) U12 Girls Div 4",
          "awayScore": "",
          "location": "MSYSL Fields - Field 3",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        },
        {
          "matchNum": "775",
          "date": "06/10/2026",
          "time": "18:30 EDT",
          "homeClub": "Rip Van Winkle",
          "homeTeam": "RVW U12 Girls Spring Travel 2026",
          "homeScore": "",
          "awayClub": "Mechanicville-Stillwater",
          "awayTeam": "MSUSC U12 Girls (Spring 2026)",
          "awayScore": "",
          "location": "Rip Van Winkle Soccer Field - Field 3",
          "division": "Division 4",
          "age": "12",
          "gender": "Female",
          "status": "",
          "eventName": "CDYSL 2026 Spring Season"
        }
      ],
      "modified": [
        {
          "matchNum": "6",
          "row": {
            "matchNum": "6",
            "date": "04/10/2026",
            "time": "19:00 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U16G",
            "homeScore": "",
            "awayClub": "Saratoga-Wilton",
            "awayTeam": "SWSC U15 Girls",
            "awayScore": "",
            "location": "Afrim's Sports Park - Afrim's Sports Park Field 4B - OUT",
            "division": "Upstate U16 Girls",
            "age": "16",
            "gender": "Female",
            "status": "Scheduled",
            "eventName": "Northeast Classic - Girls 2026"
          },
          "changes": [
            {
              "field": "Date",
              "from": "03/20/2026",
              "to": "04/10/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "19:00 EDT"
            },
            {
              "field": "Away Club",
              "from": "Greenbush Soccer Club",
              "to": "Saratoga-Wilton"
            },
            {
              "field": "Away Team",
              "from": "Greenbush SC Girls 2010/2011 (U16)-Green",
              "to": "SWSC U15 Girls"
            },
            {
              "field": "Location",
              "from": "Waterford-Halfmoon High School - HS Turf Field",
              "to": "Afrim's Sports Park - Afrim's Sports Park Field 4B - OUT"
            },
            {
              "field": "Division",
              "from": "GU16",
              "to": "Upstate U16 Girls"
            }
          ]
        },
        {
          "matchNum": "803",
          "row": {
            "matchNum": "803",
            "date": "04/18/2026",
            "time": "17:45 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U14 Boys (Spring 2026)",
            "homeScore": "",
            "awayClub": "FC Dutchmen",
            "awayTeam": "FC Dutchmen Surf STRIKERS 2012 boys NPL",
            "awayScore": "",
            "location": "MSYSL Fields - Field 4",
            "division": "Division 3",
            "age": "14",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/19/2026",
              "to": "04/18/2026"
            }
          ]
        },
        {
          "matchNum": "535",
          "row": {
            "matchNum": "535",
            "date": "05/01/2026",
            "time": "18:30 EDT",
            "homeClub": "Rotterdam",
            "homeTeam": "RUSC U12 Boys",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Rotterdam United Soccer Fields - U12 Field 1",
            "division": "Division 3",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/21/2026",
              "to": "05/01/2026"
            }
          ]
        },
        {
          "matchNum": "150",
          "row": {
            "matchNum": "150",
            "date": "05/02/2026",
            "time": "10:00 EDT",
            "homeClub": "Clifton Park",
            "homeTeam": "CPSC Evolution U8 Boys Black 25/26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U8 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Clifton Common  - U8 A",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/13/2026",
              "to": "05/02/2026"
            }
          ]
        },
        {
          "matchNum": "1259",
          "row": {
            "matchNum": "1259",
            "date": "05/03/2026",
            "time": "16:15 EDT",
            "homeClub": "FC Dutchmen",
            "homeTeam": "FC Dutchmen Surf RISING 2016 boys",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U10 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Dicaprio Park - Field 10",
            "division": "Division 3",
            "age": "10",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/12/2026",
              "to": "05/03/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "16:15 EDT"
            },
            {
              "field": "Location",
              "from": "Dicaprio Park - Field 11",
              "to": "Dicaprio Park - Field 10"
            }
          ]
        },
        {
          "matchNum": "1295",
          "row": {
            "matchNum": "1295",
            "date": "05/11/2026",
            "time": "18:30 EDT",
            "homeClub": "Otsego United Soccer, Inc.",
            "homeTeam": "Otsego United U17 Boys Spring '26",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U17 Boys (Spring 2026)",
            "awayScore": "",
            "location": "Ryder Elementary School - Ryder Elementary School Field 1",
            "division": "HS Boys Div 4",
            "age": "19",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/10/2026",
              "to": "05/11/2026"
            },
            {
              "field": "Time",
              "from": "13:00 EDT",
              "to": "18:30 EDT"
            }
          ]
        },
        {
          "matchNum": "1284",
          "row": {
            "matchNum": "1284",
            "date": "05/16/2026",
            "time": "13:00 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U17 Boys (Spring 2026)",
            "homeScore": "",
            "awayClub": "Fulton United",
            "awayTeam": "Force M U18B",
            "awayScore": "",
            "location": "MSYSL Fields - Field 4",
            "division": "HS Boys Div 4",
            "age": "19",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/19/2026",
              "to": "05/16/2026"
            }
          ]
        },
        {
          "matchNum": "652",
          "row": {
            "matchNum": "652",
            "date": "05/17/2026",
            "time": "17:45 EDT",
            "homeClub": "FC Dutchmen",
            "homeTeam": "FC Dutchmen Surf ROWDIES 2015 boys",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Reds (Spring 2026)",
            "awayScore": "",
            "location": "Dicaprio Park - Field 8",
            "division": "Division 4",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Dicaprio Park - Field 10",
              "to": "Dicaprio Park - Field 8"
            }
          ]
        },
        {
          "matchNum": "1301",
          "row": {
            "matchNum": "1301",
            "date": "05/22/2026",
            "time": "18:30 EDT",
            "homeClub": "Northern United Soccer Club",
            "homeTeam": "U19B White Lightning",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U17 Boys (Spring 2026)",
            "awayScore": "",
            "location": "Ridge/Jenkinsville - Field 2",
            "division": "HS Boys Div 4",
            "age": "19",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Ridge/Jenkinsville - Field 3",
              "to": "Ridge/Jenkinsville - Field 2"
            }
          ]
        },
        {
          "matchNum": "562",
          "row": {
            "matchNum": "562",
            "date": "05/23/2026",
            "time": "13:00 EDT",
            "homeClub": "Crane",
            "homeTeam": "FC Columbia (2026) U12 Boys Red Div 3",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "St Joseph Spiritual Center Mavis Fields - U12 Game Field",
            "division": "Division 3",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/12/2026",
              "to": "05/23/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "13:00 EDT"
            }
          ]
        },
        {
          "matchNum": "767",
          "row": {
            "matchNum": "767",
            "date": "05/29/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U12 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Albany SC",
            "awayTeam": "Blue Jays - Albany Soccer Club",
            "awayScore": "",
            "location": "MSYSL Fields - Field 3",
            "division": "Division 4",
            "age": "12",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/03/2026",
              "to": "05/29/2026"
            }
          ]
        },
        {
          "matchNum": "589",
          "row": {
            "matchNum": "589",
            "date": "06/05/2026",
            "time": "18:30 EDT",
            "homeClub": "Ballston Spa",
            "homeTeam": "Ballston Spa Soccer Club U12 Boys C",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Luther Forest Athletic Fields  - U12 FIELD 2",
            "division": "Division 3",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/02/2026",
              "to": "06/05/2026"
            }
          ]
        },
        {
          "matchNum": "1286",
          "row": {
            "matchNum": "1286",
            "date": "06/10/2026",
            "time": "18:30 EDT",
            "homeClub": "Fulton United",
            "homeTeam": "Force N U18B",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U17 Boys (Spring 2026)",
            "awayScore": "",
            "location": "Prospect Hill Cemetery - Prospect Hill Cemetery Field",
            "division": "HS Boys Div 4",
            "age": "19",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/26/2026",
              "to": "06/10/2026"
            },
            {
              "field": "Time",
              "from": "13:00 EDT",
              "to": "18:30 EDT"
            },
            {
              "field": "Location",
              "from": "Northville High School - Northville High School",
              "to": "Prospect Hill Cemetery - Prospect Hill Cemetery Field"
            }
          ]
        },
        {
          "matchNum": "139",
          "row": {
            "matchNum": "139",
            "date": "06/11/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U8 Boys Gunners (Spring 2026)",
            "homeScore": "",
            "awayClub": "Colonie",
            "awayTeam": "Colonie U8 Boys Garnet",
            "awayScore": "",
            "location": "MSYSL Fields - Field 1",
            "division": "Division 3",
            "age": "8",
            "gender": "Coed",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/01/2026",
              "to": "06/11/2026"
            }
          ]
        },
        {
          "matchNum": "1041",
          "row": {
            "matchNum": "1041",
            "date": "06/11/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U16 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Capital CIty FC",
            "awayTeam": "Capital City FC U16 Girls Integrity - CDYSL",
            "awayScore": "",
            "location": "MSYSL Fields - Field 4",
            "division": "U16G Bracket",
            "age": "16",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/07/2026",
              "to": "06/11/2026"
            },
            {
              "field": "Time",
              "from": "14:45 EDT",
              "to": "18:30 EDT"
            }
          ]
        },
        {
          "matchNum": "719",
          "row": {
            "matchNum": "719",
            "date": "06/17/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U12 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Crane",
            "awayTeam": "FC Columbia (2026) U12 Girls Div 4",
            "awayScore": "",
            "location": "MSYSL Fields - Field 3",
            "division": "Division 4",
            "age": "12",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/22/2026",
              "to": "06/17/2026"
            },
            {
              "field": "Away Club",
              "from": "Rip Van Winkle",
              "to": "Crane"
            },
            {
              "field": "Away Team",
              "from": "RVW U12 Girls Spring Travel 2026",
              "to": "FC Columbia (2026) U12 Girls Div 4"
            }
          ]
        }
      ]
    },
    {
      "fromLabel": "spring2026-v3",
      "toLabel": "spring2026-v4",
      "fromVersion": 3,
      "toVersion": 4,
      "comparedAt": "2026-03-31T19:36:23.460Z",
      "added": [],
      "removed": [],
      "modified": [
        {
          "matchNum": "1022",
          "row": {
            "matchNum": "1022",
            "date": "04/18/2026",
            "time": "11:00 EDT",
            "homeClub": "Saratoga-Wilton",
            "homeTeam": "SWSC U16 Girls",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U16 Girls (Spring 2026)",
            "awayScore": "",
            "location": "Gavin Park - Field 9",
            "division": "U16G Bracket",
            "age": "16",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/03/2026",
              "to": "04/18/2026"
            },
            {
              "field": "Time",
              "from": "14:45 EDT",
              "to": "11:00 EDT"
            },
            {
              "field": "Location",
              "from": "Gavin Park - Field 1",
              "to": "Gavin Park - Field 9"
            }
          ]
        },
        {
          "matchNum": "544",
          "row": {
            "matchNum": "544",
            "date": "04/28/2026",
            "time": "18:30 EDT",
            "homeClub": "Saratoga-Wilton",
            "homeTeam": "SWSC U12 Boys White",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Boys Gunners (Spring 2026)",
            "awayScore": "",
            "location": "Gavin Park - 6A",
            "division": "Division 3",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Gavin Park - 4.1",
              "to": "Gavin Park - 6A"
            }
          ]
        },
        {
          "matchNum": "735",
          "row": {
            "matchNum": "735",
            "date": "05/15/2026",
            "time": "18:30 EDT",
            "homeClub": "RCS Soccer Club",
            "homeTeam": "2014/15 RCS Girls",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U12 Girls (Spring 2026)",
            "awayScore": "",
            "location": "Coeyman's Landing - Coeyman's Landing Field 2",
            "division": "Division 4",
            "age": "12",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/06/2026",
              "to": "05/15/2026"
            }
          ]
        },
        {
          "matchNum": "897",
          "row": {
            "matchNum": "897",
            "date": "05/20/2026",
            "time": "18:30 EDT",
            "homeClub": "Empire State Youth Soccer Club",
            "homeTeam": "970 United Girls U14B Yellow",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U14 Girls (Spring 2026)",
            "awayScore": "",
            "location": "Shenendehowa High School - Turf Field 13",
            "division": "Division 2",
            "age": "14",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/03/2026",
              "to": "05/20/2026"
            },
            {
              "field": "Time",
              "from": "16:15 EDT",
              "to": "18:30 EDT"
            }
          ]
        },
        {
          "matchNum": "911",
          "row": {
            "matchNum": "911",
            "date": "06/03/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U14 Girls (Spring 2026)",
            "homeScore": "",
            "awayClub": "Fifty Football Club",
            "awayTeam": "Fifty FC U14 Girls 25-26",
            "awayScore": "",
            "location": "MSYSL Fields - Field 4",
            "division": "Division 2",
            "age": "14",
            "gender": "Female",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/31/2026",
              "to": "06/03/2026"
            },
            {
              "field": "Time",
              "from": "16:15 EDT",
              "to": "18:30 EDT"
            },
            {
              "field": "Away Club",
              "from": "Greenbush Soccer Club",
              "to": "Fifty Football Club"
            },
            {
              "field": "Away Team",
              "from": "Greenbush SC Girls 2012/2013 (U14)-White",
              "to": "Fifty FC U14 Girls 25-26"
            }
          ]
        },
        {
          "matchNum": "673",
          "row": {
            "matchNum": "673",
            "date": "06/04/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U12 Boys Reds (Spring 2026)",
            "homeScore": "",
            "awayClub": "Clifton Park",
            "awayTeam": "CPSC U12 Boys Yellow Jackets 25/26",
            "awayScore": "",
            "location": "MSYSL Fields - Field 3",
            "division": "Division 4",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/02/2026",
              "to": "06/04/2026"
            }
          ]
        },
        {
          "matchNum": "399",
          "row": {
            "matchNum": "399",
            "date": "06/05/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U10 Boys Lions (Spring 2026)",
            "homeScore": "",
            "awayClub": "Crane",
            "awayTeam": "FC Columbia (2026) U10 Boys Blue Div 4",
            "awayScore": "",
            "location": "MSYSL Fields - Field 2",
            "division": "Division 4",
            "age": "10",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/07/2026",
              "to": "06/05/2026"
            },
            {
              "field": "Time",
              "from": "17:45 EDT",
              "to": "18:30 EDT"
            }
          ]
        },
        {
          "matchNum": "598",
          "row": {
            "matchNum": "598",
            "date": "06/13/2026",
            "time": "13:00 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U12 Boys Gunners (Spring 2026)",
            "homeScore": "",
            "awayClub": "Crane",
            "awayTeam": "FC Columbia (2026) U12 Boys Red Div 3",
            "awayScore": "",
            "location": "MSYSL Fields - Field 3",
            "division": "Division 3",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "06/09/2026",
              "to": "06/13/2026"
            },
            {
              "field": "Time",
              "from": "18:30 EDT",
              "to": "13:00 EDT"
            }
          ]
        },
        {
          "matchNum": "407",
          "row": {
            "matchNum": "407",
            "date": "06/16/2026",
            "time": "18:30 EDT",
            "homeClub": "Saratoga-Wilton",
            "homeTeam": "SWSC U9/10 Boys White",
            "homeScore": "",
            "awayClub": "Mechanicville-Stillwater",
            "awayTeam": "MSUSC U10 Boys Lions (Spring 2026)",
            "awayScore": "",
            "location": "Gavin Park - 3A",
            "division": "Division 4",
            "age": "10",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Location",
              "from": "Gavin Park - Field 2",
              "to": "Gavin Park - 3A"
            }
          ]
        }
      ]
    },
    {
      "fromLabel": "spring2026-v4",
      "toLabel": "spring2026-v5",
      "fromVersion": 4,
      "toVersion": 5,
      "comparedAt": "2026-03-31T19:36:23.461Z",
      "added": [],
      "removed": [],
      "modified": [
        {
          "matchNum": "622",
          "row": {
            "matchNum": "622",
            "date": "04/30/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U12 Boys Reds (Spring 2026)",
            "homeScore": "",
            "awayClub": "Colonie",
            "awayTeam": "Colonie U12 Boys Garnet",
            "awayScore": "",
            "location": "MSYSL Fields - Field 3",
            "division": "Division 4",
            "age": "12",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "04/28/2026",
              "to": "04/30/2026"
            }
          ]
        },
        {
          "matchNum": "811",
          "row": {
            "matchNum": "811",
            "date": "05/01/2026",
            "time": "18:30 EDT",
            "homeClub": "Mechanicville-Stillwater",
            "homeTeam": "MSUSC U14 Boys (Spring 2026)",
            "homeScore": "",
            "awayClub": "FC Dutchmen",
            "awayTeam": "FC Dutchmen Surf RIPTIDE 2013 boys NPL",
            "awayScore": "",
            "location": "MSYSL Fields - Field 4",
            "division": "Division 3",
            "age": "14",
            "gender": "Male",
            "status": "",
            "eventName": "CDYSL 2026 Spring Season"
          },
          "changes": [
            {
              "field": "Date",
              "from": "05/10/2026",
              "to": "05/01/2026"
            },
            {
              "field": "Time",
              "from": "17:45 EDT",
              "to": "18:30 EDT"
            }
          ]
        }
      ]
    }
  ]
};
